# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - d1_arm_controller
    - d1_gripper_controller

  d1_arm_controller:
    type: FollowJointTrajectory
    joints:
      - Joint1
      - Joint2
      - Joint3
      - Joint4
      - Joint5
    action_ns: follow_joint_trajectory
    default: true
  d1_gripper_controller:
    type: FollowJointTrajectory
    joints:
      - Joint6
      - Joint_L
      - Joint_R
    action_ns: follow_joint_trajectory
    default: true